[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Magzhan <magnet.magmat@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.1"
views = "^0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
